# Generated by Django 5.2 on 2026-07-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(help_text='TwitterのユーザーID', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='ユーザー名(@の後ろ)', max_length=100)),
                ('name', models.CharField(help_text='表示名', max_length=100)),
                ('profile_image_url', models.URLField(blank=True, help_text='アイコン画像URL', null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='OAuth 2.0 アクセストークン')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth 2.0 リフレッシュトークン', null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='アクセストークンの有効期限', null=True)),
                ('totp_secret', models.TextField(blank=True, help_text='TOTP秘密鍵', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Userテーブルの参照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='users.user')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
