# Generated by Django 5.2 on 2026-07-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='access_token_expires_at',
        ),
    ]
