# Generated by Django 5.2 on 2026-09-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_initial'),
        ('tweets', '0002_initial'),
        ('users', '0002_remove_account_access_token_expires_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='XUser',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='x_user',
        ),
        migrations.AlterModelTable(
            name='xuser',
            table='x_users',
        ),
    ]
