# Generated by Django 5.2 on 2026-09-10 20:55

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_xuser_rename_user_account_x_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
    ]
