# Generated by Django 5.2 on 2026-09-10 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='x_user',
            field=models.ForeignKey(blank=True, help_text='Userテーブルの参照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='users.xuser'),
        ),
    ]
