# Generated by Django 5.2 on 2026-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(help_text='DMの会話ID', primary_key=True, serialize=False)),
                ('dm_conversation_id', models.CharField(help_text='DMの会話ID(相手と共有)', max_length=50)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='最後のメッセージ日時', null=True)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigIntegerField(help_text='DMメッセージ ID', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='DM本文')),
                ('created_at', models.DateTimeField(help_text='DM送信日時')),
            ],
            options={
                'db_table': 'direct_messages',
            },
        ),
        migrations.CreateModel(
            name='DirectMessageMedia',
            fields=[
                ('media_key', models.CharField(help_text='Xのmedia_key', max_length=50, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', '写真'), ('video', '動画'), ('animated_gif', 'gif画像')], help_text='メディアの種類', max_length=12)),
                ('url', models.CharField(help_text='メディアのURL')),
                ('alt_text', models.TextField(blank=True, help_text='代替テキスト', null=True)),
                ('width', models.IntegerField(help_text='メディアの横幅(px)')),
                ('height', models.IntegerField(help_text='メディアの縦幅(px)')),
                ('duration_ms', models.IntegerField(blank=True, help_text='動画の長さ(m秒)', null=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
    ]
