# Generated by Django 5.2 on 2026-07-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='DMの相手', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='users.user'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='DMの部屋', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='dm.conversation'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='送信者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='users.user'),
        ),
        migrations.AddField(
            model_name='directmessagemedia',
            name='direct_message',
            field=models.ForeignKey(help_text='紐づくDM', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dm.directmessage'),
        ),
    ]
