# Generated by Django 5.2 on 2026-09-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessagemedia',
            name='height',
            field=models.IntegerField(blank=True, help_text='メディアの縦幅(px)', null=True),
        ),
        migrations.AlterField(
            model_name='directmessagemedia',
            name='url',
            field=models.CharField(blank=True, help_text='メディアのURL', null=True),
        ),
        migrations.AlterField(
            model_name='directmessagemedia',
            name='width',
            field=models.IntegerField(blank=True, help_text='メディアの横幅(px)', null=True),
        ),
    ]
