# Generated by Django 5.2 on 2026-07-10 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(help_text='tweetID', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='投稿本文')),
                ('created_at', models.DateTimeField(help_text='投稿日時')),
                ('conversation_id', models.BigIntegerField(blank=True, help_text='会話ID', null=True)),
                ('in_reply_to_tweet_id', models.BigIntegerField(blank=True, help_text='リプライ先のTweet ID', null=True)),
                ('in_quoted_to_tweet_id', models.BigIntegerField(blank=True, help_text='引用先のTweet ID', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='投稿者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='users.user')),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('media_key', models.CharField(help_text='mediaのkey', max_length=50, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', '写真'), ('video', '動画'), ('animated_gif', 'gif画像')], help_text='メディアの種類', max_length=12)),
                ('url', models.URLField(blank=True, help_text='メディアのURL', null=True)),
                ('alt_text', models.TextField(blank=True, help_text='代替テキスト', null=True)),
                ('width', models.IntegerField(blank=True, help_text='メディアの横幅(px)', null=True)),
                ('height', models.IntegerField(blank=True, help_text='メディアの縦幅(px)', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='動画の長さ(ミリ秒)', null=True)),
                ('tweet', models.ForeignKey(help_text='紐づくツイート', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tweets.tweet')),
            ],
            options={
                'db_table': 'tweet_media',
            },
        ),
    ]
