# Generated by Django 5.2 on 2026-07-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(blank=True, help_text='投稿者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='users.user'),
        ),
        migrations.AddField(
            model_name='tweetmedia',
            name='tweet',
            field=models.ForeignKey(help_text='紐づくツイート', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tweets.tweet'),
        ),
    ]
